### ISSUE TITLE
'Invalid type for parameter Body' error during operation

### ISSUE THREAD

**Issue by roybenyosef** [roybenyosef/radio-epg#3]
Invalid type for parameter Body, value: {'Time': '0000-0100', 'Name': 'Top Hits', 'Description': 'אכלתי כל כך הרבה'}, type: <class 'dict'>, valid types: <class 'bytes'>, <class 'bytearray'>, file-like object
Traceback (most recent call last):
  File "/var/task/index.py", line 16, in main
    S3.put_object(Body=out_data, Bucket=os.environ['OUT_BUCKET_NAME'], Key='epg.json')
  File "/var/runtime/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/var/runtime/botocore/client.py", line 634, in _make_api_call
    api_params, operation_model, context=request_context)
  File "/var/runtime/botocore/client.py", line 682, in _convert_to_request_dict
    api_params, operation_model)
  File "/var/runtime/botocore/validate.py", line 297, in serialize_to_request
    raise ParamValidationError(report=report.generate_report())

**Comment by roybenyosef** [comment]
Save object as text
